### ISSUE TITLE
Feature request: "Collectibles" and "Bosses" tabs

### ISSUE THREAD

**Issue by boozledorf** [IdleLands/GlobalOld#11]
At the moment, the only way to find where certain collectibles and bosses are is by looking at every single map, one at a time, and poring over it until you find the "?" icon that happens to be the collectible I'm looking for.  I could also look at all of the map json files one by one and ctrl + f until I find the collectible I want.  The same is true for bosses.

It would be very helpful for people who are looking to obtain certain pets if we could easily locate where the required collectibles and bosses are.

**Comment by seiyria** [comment]
IMO that ruins most of the fun, so this is not something I will probably ever officially support. If you really want this, it's posted in [every travis build](https://travis-ci.org/IdleLands/Maps#L172) so you can look there.
