### ISSUE TITLE
new 3:

### ISSUE THREAD

**Issue by seiyria** [IdleLands/GlobalOld#20]
camping wolf
most ascensions
cumulative boss kills

**Comment by sedgwick** [comment]
Most Ascensions and Most Boss Kills

**Comment by sedgwick** [comment]
Perhaps the most ascensions should also use the information from this issue: https://github.com/IdleLands/IdleLands/issues/587

That way you could determine which player ascended first in the event that multiple people are at the same ascension level.

**Comment by sedgwick** [comment]
I realize now most levels category pretty well covers the most ascensions category, so another idea could be to have a category for the currently best equipped players based off the item score, similar to how it calculates when you ascend.

**Comment by seiyria** [comment]
can also show the number of party steps

**Comment by boozledorf** [comment]
Highest gold.gamble.win / gold.gamble.lose ratio (only include people with gold.gamble.win > 0, and list people with gold.gamble.lose = 0 separately as "Perfect Win / Loss ratio" ?)

**Comment by sedgwick** [comment]
Astral Walker
Acid Walker

**Comment by seiyria** [comment]
moving astral walker to the next set of 3
